# Generated by Django 6.0.3 on 2026-03-13 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserTracker', '0003_dailylog_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='DailyLog',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
